# Generated by Django 3.0.5 on 2020-04-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='precio_total',
            new_name='precio',
        ),
    ]
